lib/router/router.js
test/tests/router_test.js

Needed for https://github.com/emberjs/ember.js/issues/10235

Invoke willTransition router function

---

README.md

Fix build command in README

---

lib/router/unrecognized-url-error.js

This already has appropriate test coverage, which was appropriately failing.

Fix UnrecognizedURLError inheritance

---

test/tests/router_test.js
test/tests/transition_intent_test.js
test/vendor/qunit.css
test/vendor/qunit.js

Step 1 on the road to a healthier test suite.
All the test changes here have to do with the fact that tests were behaving as though they were async when in reality they weren't. With the QUnit improvements, this caused errors because QUnit would attempt to restart and complain that it never stopped.
(Note: we should probably not check QUnit into the repo, but I'll leave changing the build pipeline for another time.)

Bump QUnit to last 1.x release

---

lib/router/handler-info.js

Stupid Phantom 1.9. :rage:
Fixes #188.

Use Object.defineProperty over getter/setter.

---

lib/router/transition.js
test/tests/router_test.js

Addresses https://github.com/emberjs/ember.js/issues/14268.

Ensure `Transition#isActive` is initially truthy.

---

test/tests/async_get_handler_test.js

Verifies the behavior we want out of https://github.com/tildeio/router.js/issues/193.
cc/ @rwjblue @nathanhammond

Add test to verify execution order of hooks in async handlers

---

README.md

Improve nesting documentation

---

README.md

Add example history implementations to README.

---

README.md

This isn't ready for merge just yet, but it will be once https://github.com/tildeio/route-recognizer/commit/0499446f80c649a2df64ced5cc5458742a57c423 is released.

Update README to reflect matching algorithm.

---

test/tests/router_test.js

Add tests demonstrating that #60 is resolved

---

lib/router/utils.js

since ember.js already using native isArray, I think it can be removed ?

removed `isArray` fallback

---

lib/router/router.js

this is strange but this code is not used

removed unused code

---

lib/router/router.js

Compare with [line 24](https://github.com/tildeio/router.js/compare/master...chriskrycho:patch-1#diff-ccd76929358a61054445c927c7746ef4R24).

Remove duplicate `this.state` assignment.

---

README.md

This PR changes the build badges to SVG for sharper readability ✨

README: SVG badges

---

lib/router/transition.ts
tests/router_test.ts

Per the RFC `from` should start out as `null` not `undefined`.

[BUGFIX] Transition.from should be null not undefined

---

lib/router/router.ts
tests/router_test.ts

Should fix https://github.com/emberjs/ember.js/issues/17164

[BUGFIX] Ensure activeTransiton

---

lib/router/router.ts
tests/router_test.ts

Fixes https://github.com/emberjs/ember.js/issues/17430
Verified in the reproduction.

Fix transition being undefined through substates

---

lib/router/route-info.ts

for metadata if they are not resolved

[bugfix] Async routes should return promises

---

lib/router/route-info.ts
lib/router/router.ts
lib/router/transition-intent/named-transition-intent.ts
lib/router/transition-state.ts
lib/router/transition.ts
lib/router/utils.ts
package.json
tests/route_info_test.ts
tests/router_test.ts
tests/test_helpers.ts
yarn.lock

Seems there's still some incorrect typing need to be fixed.

Upgrade typescript

---

package.json
yarn.lock

Excludes `broccoli-babel-transpiler` (needs more work to update).

Update remaining dependencies/devDependencies to latest.

---

.github/workflows/ci.yml
.prettierrc
package.json

* use volta
* test across multiple node versions and OS's
* run tests weekly on sundays to catch odd things

Upgrade CI

---

lib/router/route-info.ts
lib/router/transition-intent/named-transition-intent.ts
lib/router/transition-intent/url-transition-intent.ts

This appears to be internal, code searches seem to confirm this.

[fixes #313] Fix Typo shouldSupercede -> shouldSupersede

---

.eslintrc.js
.github/workflows/ci.yml
lib/router/index.ts
lib/router/route-info.ts
lib/router/router.ts
lib/router/transition-intent.ts
lib/router/transition-intent/named-transition-intent.ts
lib/router/transition-intent/url-transition-intent.ts
lib/router/transition-state.ts
lib/router/transition.ts
lib/router/utils.ts
package.json
tests/query_params_test.ts
tests/route_info_test.ts
tests/router_test.ts
tests/test_helpers.ts
tests/transition-aborted-error_test.ts
tests/transition_intent_test.ts
tests/transition_state_test.ts
yarn.lock

I have a PR for Ember ready to go using these updated types.

Better Types

---

package.json
yarn.lock

Now will use our specified TypeScript

Upgrade broccoli-typescript-compiler

---

lib/router/index.ts
lib/router/route-info.ts
lib/router/router.ts
lib/router/transition-intent.ts
lib/router/transition-intent/named-transition-intent.ts
lib/router/transition-intent/url-transition-intent.ts
lib/router/transition-state.ts
lib/router/transition.ts
tests/query_params_test.ts
tests/router_test.ts
tests/test_helpers.ts
tests/transition_intent_test.ts
tests/transition_state_test.ts

See https://github.com/emberjs/ember.js/issues/19949

Loosen route generics

---

lib/router/route-info.ts
tests/router_test.ts

fixes https://github.com/emberjs/ember.js/issues/20056

fix undefined routeInfo in routeInfos.find's callback
