README.md
The code used to reference an undefined `posts` variable and did not use the passed parameter `object`. Later on down serialize is used again but does use its passed parameter, indicating that this one may be wrong.
=> Correcting example function in README

lib/router/handler-info/unresolved-handler-info-by-object.js, lib/router/router.js, lib/router/transition-intent/named-transition-intent.js, test/tests/router_test.js, test/tests/transition_intent_test.js
Allows the logic for linking to a route (e.g., constructing urls) to be separated from the logic needed to enter a route.
This is a corollary to the [Route Serializers RFC from Ember.js](https://github.com/emberjs/rfcs/blob/master/text/0120-route-serializers.md). The main goal here is to enable URLs/links for a route to be constructed _before_ a route's handler has been loaded. This will help enable the ability to lazy-load routes. The next step will be to allow `getHandler` to return a Promise value for a handler.
cc @dgeb @rwjblue
=> Introduce getSerializer option

.jshintrc, test/tests/handler_info_test.js, test/tests/query_params_test.js, test/tests/router_test.js, test/tests/test_helpers.js, test/tests/transition_intent_test.js, test/tests/transition_state_test.js, test/tests/unrecognized-url-error_test.js, test/tests/utils_test.js
Step 3 in improving test help.
The number of allowed globals was too high. In particular, the tests all used the QUnit globals which have been deprecated and removed in 2.x. This helps keep tests more atomic.
Remaining piece after this will be to extract the pseudo-async backburner logic to give better guarantees about testing actually async behavior.
=> Restrict globals usage and remove QUnit globals usage

lib/router/handler-info.js, lib/router/handler-info/unresolved-handler-info-by-object.js, lib/router/transition-intent/named-transition-intent.js, lib/router/transition-intent/url-transition-intent.js, package.json, test/tests/router_test.js
Currently, `getHandler` is called before constructing a `HandlerInfo` object. This
results in work being done upfront even if the `handler` property of the
`HandlerInfo` is never accessed. This change invokes `getHandler` only when the
value is actually needed.
This is particularly needed in the case of `getHandler` fetching lazily-loaded
routes. Previously lazy routes would be fetched even if the router was just
generating a URL; a task which can be done without the whole handler.
Note: This change relies on getters/setters which implies IE9+ support (which is in line with Ember's support policy, but I am unsure about this library itself).
=> Get handlers lazily

lib/router/handler-info.js
@rwjblue I think your PR #189 missed the `handlerPromise` property. Was still getting a PhantomJS crash as reported in #188 , even with the lastest canary build. This should hopefully fix it! :)
=> Use Object.defineProperty over getter/setter also for handlerPromise

lib/router/router.js, lib/router/transition.js, test/tests/router_test.js
This has been broken forever AFAIK, and is surprising to a lot of people. In
fact, even the ember guides recommend [using `this.transitionTo` for redirecting](https://guides.emberjs.com/v2.9.0/routing/redirection/)
This is in fact broken. If you use `transitionTo` as a redirect strategy,
then you get an extra history entry if you hit the route as the first route in
your app. This breaks the back button, as the back button takes you to the route
with the redirect, then immediately redirects back to the page you're on.
Maybe you can go back if you hammer back button really quickly, but you have to
hammer it loads super quick. Not a good UX.
`replaceWith` works if you use it to redirect from a route that's your
initial transition. However if you use it to redirect and you hit that route
from …
=> Fix validation stage redirection behaviour.

lib/router/router.js, lib/router/transition-aborted-error.js, lib/router/transition.js, lib/router/unrecognized-url-error.js, test/tests/router_test.js, test/tests/test_helpers.js, test/tests/transition-aborted-error_test.js
@rwjblue how does this look?
- Inherit from `Error`
- Cleanup tests to use a shared helper
- Test to ensure that TransitionAbortedError has the correct name
- Improve stacktrace capturing
fixes #174
=> Improve errors

lib/router/router.js, lib/router/transition-aborted-error.js, lib/router/transition.js, lib/router/unrecognized-url-error.js, test/tests/router_test.js, test/tests/test_helpers.js, test/tests/transition-aborted-error_test.js
- Inherit from `Error`
- Cleanup tests to use a shared helper
- Test to ensure that TransitionAbortedError has the correct name
- Improve stacktrace capturing
(originally in #44ec3a3e)
The offender was `let` (https://github.com/tildeio/router.js/commit/44ec3a3e7322335b064ff5a548a0ceab9e07c39d#diff-27ceedfd6b26d554a7f028b0483acc50R8). `npm test` now runs without trouble.
fixes #203
cc @rwjblue
=> Reinstate improve errors

lib/router/router.js, test/tests/query_params_test.js
This property has been set incorrectly on some transitions, notably when the
transition is caused by the Router#refresh() method in queryParamsDidChange.
This is the method ember uses to implement `refreshModel` option of query params,
so fixing this bug allows `refreshModel` to be used in conjunction with
`replace` option for query params, currently it is either-or.
Resolves emberjs/ember.js#10577 and emberjs/ember.js#11843
=> Fix queryParamsOnly being correct on transitions.

lib/router/router.js, test/tests/query_params_test.js
So I fixed this in #198. But it was broken again by #197 and the tests didn't
catch that. So I've improved the tests and fixed it again.
@rwjblue I think you were looking at this last time
Ember issue: emberjs/ember.js#11843
Ember failing test PR: emberjs/ember.js#15148
=> Fix query params refresh transitions if they are using replaceState

lib/router/transition.js, test/tests/router_test.js
Prior to this change retrying the transition would convert the `replaceWith` in
a regular `transitionTo`.
Example code (assuming `this` is an Ember route):
```js
let transition = this.replaceWith('new.route');
transition.abort();
session.set('attemptedTransition', transition);
session.authenticate('authenticator:devise').authenticate(username, password); // Successful authentication will call `session.get('attemptedTransition').retry()`
```
=> If a transition initiated with `replaceWith`, it's retry is also a replace.

lib/router/transition.js, test/tests/router_test.js, test/tests/test_helpers.js
Attempting to recreate the scenario identified in https://github.com/emberjs/ember.js/issues/15190.
=> Ensure initial transition can be aborted then retried.

lib/router/handler-info.js
Previously, we had nearly identical logic in the `constructor` and `fetchHandler` methods. This refactor extracts a `_processHandler` method that both can use and ensures that all setup goes through the same pathway.
=> Unify HanlderInfo#handler setup.

lib/router/handler-info/unresolved-handler-info-by-object.js, tests/router_test.js
I hit this issue in an Ember application where `this` in the `serialize` hook inside a router was undefined. I guess this is a bug.
Not sure whether the same should be done for `this.serializer` on the line that I've changed. I'm also not sure that I've handled the `async` case in the tests correctly - I just ignore it.
I'm willing to fix anything that you don't like in this PR. :)
=> Bind the serialize handler to the correct "this"

lib/router/handler-info.js, lib/router/transition-intent/named-transition-intent.js, tests/router_test.js
Fixes:
- https://github.com/emberjs/ember.js/issues/12419
- https://github.com/emberjs/ember.js/issues/10989
- https://github.com/emberjs/ember.js/issues/10195
- https://github.com/tildeio/router.js/issues/236
- https://github.com/emberjs/ember.js/issues/16275
=> Prevent context matching if the oldContext is null

lib/router/utils.js
fix `{{url-for 'posts' (hash queryParams=paramsHash)}}` use case
=> Fix a crash when (hash) helper is used to create queryParams object

lib/router/router.ts
it seems the typing is wrong. [here the constructor is used without specifying a delegate](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/router.js#L84). This is no code change.
=> make delegate optional

lib/router/handler-info.ts, lib/router/index.ts, lib/router/router.ts, lib/router/transition-intent/named-transition-intent.ts, lib/router/transition.ts, lib/router/utils.ts, tests/async_get_handler_test.ts, tests/query_params_test.ts, tests/router_test.ts, tests/test_helpers.ts
This moves the Router class to an abstract class and forces the implementation of the following methods:
```ts
abstract getHandler(name: string): IHandler | Promise<IHandler>;
abstract getSerializer(name: string): SerializerFunc | undefined;
abstract updateURL(url: string): void;
abstract replaceURL(url: string): void;
abstract willTransition(
oldHandlerInfos: HandlerInfo[],
newHandlerInfos: HandlerInfo[],
transition: Transition
): void;
abstract didTransition(handlerInfos: HandlerInfo[]): void;
abstract triggerEvent(
handlerInfos: HandlerInfo[],
ignoreFailure: boolean,
name: string,
args: unknown[]
): void;
```
Simultaneously, this removes the fallback behavior if these methods are not implemented. Specifically calls to `trigger` have been completely removed and replaced with just …
=> [BREAKING] Router Abstract Base class

.travis.yml, jsconfig.json, lib/router/index.ts, lib/router/route-info.ts, lib/router/router.ts, lib/router/transition-intent.ts, lib/router/transition-intent/named-transition-intent.ts, lib/router/transition-intent/url-transition-intent.ts, lib/router/transition-state.ts, lib/router/transition.ts, package.json, tests/async_get_handler_test.ts, tests/handler_info_test.ts, tests/query_params_test.ts, tests/router_test.ts, tests/test_helpers.ts, tests/transition_intent_test.ts, tests/transition_state_test.ts
This introduces the public `RouteInfo` type and `from` and `to` fields on the `Transition` as described in https://github.com/emberjs/rfcs/pull/95.
This PR also:
- [Breaking] removes all underscore methods from the `Route` type.
- [Breaking] Renames `HandlerInfo` -> `RouteInfo` in many places.
=> [Breaking] RouteInfo Type And Transition.(from|to)

lib/router/index.ts, lib/router/route-info.ts, lib/router/router.ts, lib/router/transition-intent.ts, lib/router/transition-intent/named-transition-intent.ts, lib/router/transition-intent/url-transition-intent.ts, lib/router/transition-state.ts, lib/router/transition.ts, lib/router/utils.ts, lib/rsvp/index.d.ts, tests/async_get_handler_test.ts, tests/handler_info_test.ts, tests/query_params_test.ts, tests/router_test.ts, tests/test_helpers.ts, tests/transition_intent_test.ts, tests/transition_state_test.ts
This makes the abstract router class generic over a type that extends the `Route` interface. This allows consumers like Ember to get the type feed back through out its implementation.
=> [BREAKING] Generics

lib/router/transition.ts
The RSVP module is going to resolve to the definitively types types which have issues. This has lead to issues in integration https://travis-ci.org/emberjs/ember.js/jobs/433121220.
=> Make Promise a partial type

lib/router/route-info.ts, lib/router/router.ts, lib/router/transition-intent/url-transition-intent.ts, lib/router/transition.ts, tests/async_get_handler_test.ts, tests/handler_info_test.ts, tests/query_params_test.ts, tests/router_test.ts, tests/test_helpers.ts, tests/transition_intent_test.ts, tests/transition_state_test.ts
This introduces two new event types `routeWillChange` and `routeDidChange`. These events are specified by the [Router Service RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#new-events-routewillchange--routedidchange). Unlike the `willTransition` and `didTransition` hooks the new events see all transition events including aborts and errors.
In the case of the error we have always aborted the transition. However, the mechanics here are somewhat problematic since calling `abort` will result in a `routeWillChange` event. To deal with this reality, we have decoupled `abort` from the functionality that rolled back the state of the transition. We have also forced the implementer to handle the transition error. In doing so the host can decide how to handle the error …
=> Add routeWillChange, routeDidChange, transitionDidError

lib/router/route-info.ts, lib/router/router.ts
Having a `reset` method on a route could very likely clobber some user space implementation. This is likely a better name for the framework defined hook.
=> Fix clobbering issue with `reset`

lib/router/route-info.ts, lib/router/router.ts, tests/router_test.ts
This adds 2 new APIs that were defined in https://github.com/emberjs/rfcs/pull/95.
- `recognize`: Takes a string URL and returns a `RouteInfo` for the leafmost route represented by the URL. Returns null if the URL is not recognized. This method expects to receive the actual URL as seen by the browser including the app's `rootURL`.
- `recognizeAndLoad`: Takes a string URL and returns a promise that resolves to a `RouteInfoWithAttributes` for the leafmost route represented by the URL. The promise rejects if the URL is not recognized or an unhandled exception is encountered. This method expects to receive the actual URL as seen by the browser including the app's rootURL.
=> Add recognize and recognizeAndLoad

lib/router/index.ts, lib/router/route-info.ts, lib/router/router.ts, lib/router/transition.ts, tests/router_test.ts
We want to be able to discourage touch state on the transition objects and force people to use the public `RouteInfo` objects. To achieve this we need to have a privileged way of accessing the state. In Ember we will install a getter on the transition and tell them to just use the router service when they access the state.
=> Use 'symbols' for accessing state on transition

lib/router/router.ts, tests/router_test.ts
Prior to this bugfix the URL was not correct in `routeDidChange` events since `didTransition` is used to update the state of the world.
=> [BUGFIX] url should be correct in the hooks

lib/router/router.ts, tests/router_test.ts
After doing some investigation we really need to rationalization QP finalization. The reason why saving off the Route Recognizer QPs is required is because `finalizeQueryParamChange` basically is a [validation step](https://github.com/tildeio/router.js/blob/master/lib/router/router.ts#L728) from the host. In the case of Ember, only QPs that are on the controller are [considered valid](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/route.ts#L2418). Unless the "valid" QPs are returned we will effectively return a new empty object [here](https://github.com/tildeio/router.js/blob/master/lib/router/router.ts#L738-L746). This then mutates the [old transition state](https://github.com/tildeio/router.js/blob/master/lib/router/router.ts#L125-L129) …
=> [BUGFIX] Fix mutable QPs through evented hooks

lib/router/router.ts, tests/router_test.ts
Prior to this change we would never see the `RouteInfo` going back to the initial destination. Since error states and loading states are different we must check how the `activeTransition` came to be and if it is simply entering a loading state construct a new `Transition` to represent the state change. This keeps the original transition retained and un-mutated.
=> [BUGFIX] RouteInfo should correctly reflect substate transitions

lib/router/route-info.ts, package.json, tests/router_test.ts, yarn.lock
This is the router.js work required for https://github.com/emberjs/rfcs/pull/398
=> [FEATURE] buildRouteInfoMetadata

lib/router/utils.ts
The wrong "arg[ument]s" variable is being checked for length, which results in logging calls to log always being logged wrong. (#281)
Current:
`log(router, "foo")` => `Transition #: foo` (arguments.length === 2, args.length === 1)
`log(router, 1, "foo)` => `1` (arguments.length === 3, args.length === 2)
Expected:
`log(router, "foo")` => `foo`
`log(router, 1, "foo)` => `Transition #1: foo`
=> [BUGFIX] Incorrect logging of messages with sequence numbers (tildeio/router.js#281)

lib/router/route-info.ts, lib/router/transition-intent/named-transition-intent.ts, tests/test_helpers.ts
This is simply bringing back this functionality:
https://github.com/tildeio/router.js/blob/v2.0.0-beta.4/lib/router/handler-info.js#L66-L67
And
https://github.com/tildeio/router.js/blob/v2.0.0-beta.4/lib/router/transition-intent/named-transition-intent.js#L58
=> Fix `refresh` in Engines

lib/router/transition-intent/named-transition-intent.ts
While debugging some routing errors on deeply nested routes with many parameters, it became difficult to track what parameters were missing. This collects all missing parameters and adds that to the error message.
=> Make missing parameter error more descriptive

ember-cli-build.js, package.json, tests/router_test.ts, yarn.lock
ci is using node 6 and several packages were already requiring node 6 so I guess this is fine...
=> Upgrade ember-cli, linting deps, etc

.travis.yml, lib/router/route-info.ts
Closes: https://github.com/tildeio/router.js/issues/291
It seems with Babel polyfill included `Object.isFrozen` vs `Object.isExtensible` has different meaning:
This change was tested on:
* IE 10
* Chrome v27+
* Chrome latest
* IE 9 (has some other non related failure)
See screenshots below:
**IE 9:**
**IE 10:**
**Chrome v27**
=> Fix crashing with Babel polyfill / Chrome <= v37.0

lib/router/router.ts, tests/router_test.ts
https://github.com/emberjs/ember.js/issues/18568
=> Update queryParamsTransition to not change QueryParams if transition has been aborted

ember-cli-build.js, lib/router/transition.ts, package.json, yarn.lock
Expose a few nice debugging tools when working with a transition:
```ts
interface Transition {
/**
In non-production builds, this function will return the stack that this Transition was
created within. In production builds, this function will not be present.
@method debugCreationStack
@return string
*/
debugCreationStack?: () => string | undefined;
/**
In non-production builds, this function will return the stack that this Transition was
aborted within (or `undefined` if the Transition has not been aborted yet). In production
builds, this function will not be present.
@method debugAbortStack
@return string
*/
debugAbortStack?: () => string | undefined;
/**
In non-production builds, this property references the Transition that _this_ Transition
was derived from or `undefined` if this …
```
=> Add better Transition debugging information.

ARCHITECTURE.md, lib/router/router.ts, lib/router/transition-aborted-error.ts, lib/router/transition-intent.ts, lib/router/transition-intent/url-transition-intent.ts, lib/router/transition-state.ts, lib/router/transition.ts, lib/router/unrecognized-url-error.ts, lib/rsvp/index.d.ts, tests/query_params_test.ts, tests/route_info_test.ts
These should largely be cosmetic, but have been tested when linked against ember to be sure.
=> Fix other typo’s

lib/router/route-info.ts, lib/router/transition-state.ts, lib/router/transition.ts, tests/route_info_test.ts, tests/transition_state_test.ts
* Reduce extraneous promise creation
* Remove `Continuation` system (use `transition.isAborted` directly)
=> Simplify TransitionState resolution system.

lib/router/route-info.ts, lib/router/router.ts, lib/router/transition-aborted-error.ts, lib/router/transition-state.ts, lib/router/transition.ts, tests/test_helpers.ts, tests/transition-aborted-error_test.ts
Migrate `TransitionAbortedError` to builder + interface.
TODO:
=> Refactor TransitionAbort to builder interface

package.json
Add the missing type file. I verified tslint pass on ember.js and intellisense works :)
=> Publish type declaration

lib/router/transition-intent/named-transition-intent.ts, tests/router_test.ts
related to https://github.com/emberjs/ember.js/pull/19448
Previously, the assertion on line 5400 would have failed
=> Ensure query params are preserved through an intermediate loading state transition

lib/router/router.ts, lib/router/transition.ts
This is a prerequisite to fix https://github.com/emberjs/ember.js/issues/19449
cc/ @rwjblue
=> introduce isIntermediate flag in transition

README.md
This PR changes getHandler method in README to getRoute.
=> README: change getHandler to getRoute

lib/router/route-info.ts, lib/router/router.ts, tests/router_test.ts
**Problem Statement**
Calling router.recognize with a URL which matches the current route affects the transition.from.queryParams for subsequent transitions. I've created a [failing test here](https://github.com/tildeio/router.js/pull/336/files#diff-aff3d7c97cdfdd7d115fdcb826ff38eba2f43ecc9133a84db6c0a2ad1720c483R1327).
**Root Cause**
The root cause appears to be caused by the fact that `toReadOnlyRouteInfo` ([source](https://github.com/tildeio/router.js/blob/9320c7b1c1e887e73afd3700cd0093b9f34c9e6b/lib/router/route-info.ts#L63)) closes over a WeakMap for `ROUTE_INFOS` which is then mutated on subsequent calls (including calls from router.recognize).
**Proposed Solution**
This PR adds a new argument to `toReadOnlyRouteInfo`, `localizeMapUpdates`, which allows the function to conditionally …
=> Calling recognize should not affect the transition.from query params for subsequent transitions

lib/router/route-info.ts
Fixes https://github.com/emberjs/ember.js/issues/20500
cc @wagenet
=> Fix a type error when `exactOptionalPropertyTypes` is enabled

lib/router/transition.ts, tests/router_test.ts
The previous implementation of `followRedirects()` would catch a transition rejection and check the router for an `activeTransition`. This can become problematic in async situations because the destination transition may have resolved before the `reject` is scheduled on the previous transition. One such case is when redirecting from an async model hook to a destination route with synchronous model hooks.
This commit updates the `followRedirects()` logic to explicitly follow the redirect chain rather than relying on the presence of an `activeTransition`. This makes following redirects work correctly regardless of any scheduling concerns.
This problem has been noted in the context of the `visit()` test helper:
- https://github.com/emberjs/ember-test-helpers/issues/332
- …
=> Fix followRedirects when source is async and destination is sync
